# Generated by Django 2.2.4 on 2019-08-26 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicao',
            options={'verbose_name': 'Medições'},
        ),
    ]
