# Generated by Django 2.2.4 on 2019-08-26 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantcontrol', '0002_auto_20190826_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dataPlantio', models.DateTimeField()),
                ('numColheitas', models.PositiveIntegerField(default=0)),
                ('dataUltimaColheita', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
            },
        ),
        migrations.AlterModelOptions(
            name='medicao',
            options={'verbose_name': 'Medição', 'verbose_name_plural': 'Medições'},
        ),
        migrations.CreateModel(
            name='Rega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRega', models.DateTimeField(auto_now_add=True)),
                ('planta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plantcontrol.Planta')),
            ],
        ),
        migrations.AddField(
            model_name='medicao',
            name='planta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plantcontrol.Planta'),
        ),
    ]
