# Generated by Django 2.2.4 on 2019-08-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantcontrol', '0003_auto_20190826_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='dataUltimaColheita',
            field=models.DateTimeField(null=True),
        ),
    ]
